
icons = {
    'camera': u'\ue90f',
    'mic': u'\ue91e',
    'copy': u'\ue925',
    'folder': u'\ue92f',
    'open-folder': u'\ue930',
    'save': u'\ue962',
    'undo': u'\ue962',
    'redo': u'\ue968',
    'sliders': u'\ue992',
    'gear': u'\ue994',
    'trash': u'\ue9ac',
    'power': u'\ue9b6',
    'warning': u'\uea07',
    'blocked': u'\uea0e',
    'x': u'\uea0f',
    'check': u'\uea10',
    'play': u'\uea1c',
    'pause': u'\uea1d',
    'stop': u'\uea20',
    'up-arrow-1': u'\uea41',
    'right-arrow-1': u'\uea42',
    'down-arrow-1': u'\uea43',
    'left-arrow-1': u'\uea44',
    'rotate': u'\ue984',
    'left-arrow-2': u'\uea40',
    'record': u'\uea56',
    '+': u'\uea0a',
    '-': u'\uea0b'
}